name: Update Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run-engine:
    permissions: write-all
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ github.repository_owner }}
      GITHUB_REPO: Universal-Proxy-Finder
      PROXY_SOURCES_URL: |
        https://raw.githubusercontent.com/4n0nymou3/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_1.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_1.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_2.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_2.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_3.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_3.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_4.txt
        https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_4.txt
        https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt
        https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt
        https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/all_configs.txt
        https://raw.githubusercontent.com/itsyebekhe/PSG/main/lite/subscriptions/xray/normal/mix
        https://raw.githubusercontent.com/itsyebekhe/PSG/main/subscriptions/xray/base64/mix
        https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
        https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/all.txt
        https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vless.txt
        https://raw.githubusercontent.com/hsb4657/v2ray/main/lastest.txt
        https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
        https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/yudou66.txt
        https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/mix.txt
        https://raw.githubusercontent.com/Mahanfix/v2rayvpn/main/mahanfix
        https://raw.githubusercontent.com/Mr8AHAL/v2ray/main/SERVER.txt
        https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
        https://raw.githubusercontent.com/Surfboardv2ray/Subs/main/Raw
        https://raw.githubusercontent.com/imohammadkhalili/V2RAY/main/Mkhalili
        https://raw.githubusercontent.com/LonUp/NodeList/main/V2RAY/Latest_base64.txt
        https://raw.githubusercontent.com/YasserDivaR/pr0xy/main/ShadowSocks2021.txt
        https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/v2ray.txt
        https://raw.githubusercontent.com/gitbigg/dy/main/jd
        https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vmess.txt
        https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
        https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
        https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/V2ray.txt
        https://raw.githubusercontent.com/dalazhi/v2ray/main/v2ray%E8%AE%A2%E9%98%85
        https://raw.githubusercontent.com/dalazhi/v2ray/main/v2ray订阅
        https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/output/converted.txt
        https://raw.githubusercontent.com/vxiaov/free_proxies/main/links.txt
        https://raw.githubusercontent.com/amin4139/share_file/main/Fastly_ConfigTestV2rayNG
        https://raw.githubusercontent.com/freefq/free/master/v2
        https://raw.githubusercontent.com/Strongmiao168/v2ray/main/yuanheng
        https://raw.githubusercontent.com/lflflf999/0516/main/BX-JD
        https://raw.githubusercontent.com/kaoxindalao/v2raycheshi/main/v2raycheshi
        https://raw.githubusercontent.com/chongdong1230/dxz/main/v2ray
        https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
        https://raw.githubusercontent.com/resasanian/Mirza/main/sub
        https://raw.githubusercontent.com/miladtahanian/V2RayCFGDumper/main/config.txt
        https://raw.githubusercontent.com/theGreatPeter/v2rayNodes/main/nodes.txt
        https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY_BASE64.txt
        https://raw.githubusercontent.com/yaney01/Yaney01/main/temporary
        https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/server.txt
        https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet_iOS.txt
        https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector_Py/main/sub/Mix/mix.txt
        https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
        https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/splitted/mixed
        https://raw.githubusercontent.com/mheidari98/.proxy/main/all
        https://raw.githubusercontent.com/LalatinaHub/Mineral/master/result/nodes
      V2RAY_RESULT_PATH: Output/v2ray_subscription.txt
      SINGBOX_RESULT_PATH: Output/singbox_subscription.json
      CONNECTION_TIMEOUT_MS: 5000
      MAX_THREADS: 128
      SINGBOX_EXECUTABLE_PATH: sing-box
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install Sing-box
        run: |
          wget -q -O sing-box.deb "https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box_1.11.15_linux_amd64.deb"
          sudo dpkg -i sing-box.deb
          sudo apt-get -f install -y

      - name: Restore Dependencies
        run: dotnet restore App/ProxyFinder.csproj

      - name: Run Proxy Finder Engine
        run: dotnet run --project App/ProxyFinder.csproj --configuration Release
