name: Update Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run-engine:
    permissions: write-all
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ github.repository_owner }}
      GITHUB_REPO: Universal-Proxy-Finder
      PROXY_SOURCES_URL: |
        # لیست URL‌ها بدون تغییر
      V2RAY_RESULT_PATH: Output/v2ray_subscription.txt
12:45:02 AM
      SINGBOX_RESULT_PATH: Output/singbox_subscription.json
      CONNECTION_TIMEOUT_MS: 5000
      MAX_THREADS: 128
      SINGBOX_EXECUTABLE_PATH: sing-box
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install Sing-box
        run: |
          wget -q -O sing-box.deb "https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box_1.11.15_linux_amd64.deb"
          sudo dpkg -i sing-box.deb
          sudo apt-get -f install -y

      - name: Create Output Directory
        run: mkdir -p Output

      - name: Restore Dependencies
        run: dotnet restore App/ProxyFinder.csproj  # یا ProxyFinder.sln اگر از Solution استفاده می‌کنید

      - name: Build Project
        run: dotnet build App/ProxyFinder.csproj --configuration Release --no-restore

      - name: Run Proxy Finder Engine
        run: dotnet run --project App/ProxyFinder.csproj --configuration Release --verbosity detailed

      - name: Check Output Files
        run: ls -l Output/

      - name: Commit and Push Output Files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Output/*
          git commit -m "Update proxy configuration files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
